module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#ffba37",
        "on-primary": "#432c00",
        "on-primary-fixed": "#281900",
        "tertiary-fixed-dim": "#b5c8df",
        "on-tertiary-fixed": "#091d2e",
        "surface": "#131313",
        "primary-fixed-dim": "#ffba37",
        "secondary": "#c7c6c6",
        "on-surface-variant": "#c4c7c7",
        "primary-fixed": "#ffdeac",
        "secondary-container": "#464747",
        "surface-dim": "#131313",
        "outline-variant": "#444748",
        "on-tertiary-container": "#75879c",
        "inverse-primary": "#7e5700",
        "error-container": "#93000a",
        "outline": "#8e9191",
        "on-secondary-container": "#b6b5b4",
        "tertiary-container": "#0c1f30",
        "surface-bright": "#393939",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#464747",
        "on-tertiary-fixed-variant": "#36485b",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary": "#303030",
        "inverse-on-surface": "#313030",
        "tertiary-fixed": "#d1e4fb",
        "secondary-fixed-dim": "#c7c6c6",
        "on-background": "#e5e2e1",
        "secondary-fixed": "#e3e2e2",
        "surface-container": "#201f1f",
        "on-tertiary": "#203243",
        "on-primary-container": "#b17c00",
        "primary": "#ffba37",
        "primary-container": "#2b1b00",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#604100",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-variant": "#353534",
        "on-surface": "#e5e2e1",
        "tertiary": "#b5c8df",
        "error": "#ffb4ab",
        "surface-container-highest": "#353534",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e2e1",
        "background": "#131313"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
